# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dr01fs01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr01FI01_IV', models.IntegerField()),
                ('dr01FI02_CV', models.CharField(max_length=250)),
                ('dr01FI03_EV', models.EmailField(max_length=250)),
                ('dr01FI05_DT', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
