# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp_Directory01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dr01fs01',
            new_name='dr01fs01_inpt1',
        ),
    ]
