# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dr02fs01_inpS1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr02fs01_Char1', models.CharField(max_length=250)),
                ('dr02fs01_Char2', models.CharField(max_length=250)),
                ('dr02fs01_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dr02fs01_inptS2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr02fs01_Char3', models.CharField(max_length=250)),
                ('dr02fs01_FChar1', models.ManyToManyField(to='dp_Directory02.dr02fs01_inpS1')),
            ],
        ),
    ]
