# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dp_Directory03', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
