# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_Directory03', '0002_auto_20171115_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
